version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  onchain-merklized-issuer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
